version: '3.7'

services:
    pet-diary:
        build: .
        container_name: pet-diary-run
        networks:
            - app
        ports:
            - 3000:3000
        volumes:
            - ./:/app

networks:
   app:
